# Generated by Django 5.0.2 on 2024-03-06 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_campanha_delete_doador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='', max_length=100)),
                ('data_nascimento', models.DateField()),
                ('whatsapp', models.IntegerField()),
                ('email', models.CharField(default='', max_length=100)),
                ('genero', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14)),
                ('forma_de_doacao', models.CharField(max_length=30)),
                ('periodicidade_doacao', models.CharField(max_length=30)),
                ('valor_doacao', models.CharField(max_length=30)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Campanha',
        ),
    ]
